### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by waqadeer** [duncan3dc/speaker#10]
Hi
API look great BUT...
I need to know how could it be installed to my scratch php application. 
I cloned via git and then `composer install`. 

Kindly tell me other steps. Thanks

**Comment by duncan3dc** [comment]
Hi Wisam,

You don't need to clone the library, to install you'd do something like:
```sh
cd ~/dev/my-php-application
composer require duncan3dc/speaker
```
Then in your application you need to include the composer autoloader:
```php
require "vendor/autoload.php";
```

After that you just use the classes as shown in the docs, good luck

**Comment by waqadeer** [comment]
I am using Yii2 framework. I got an error while installing after the following command
`composer require duncan3dc/speaker`

ERROR:
```
  Problem 1
    - Installation request for duncan3dc/speaker ^1.0 -> satisfiable by duncan3dc/speaker[1.0.0].
    - Conclusion: remove symfony/console v3.4.3
    - Conclusion: don't install symfony/console v3.4.3
    - duncan3dc/speaker 1.0.0 requires symfony/process ^2.3 -> satisfiable by symfony/process[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - symfony/process v2.3.0 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.3.1 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.3.10 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.3.11 conflicts with symfony/console[v3.4.3].
```
...
```
 - symfony/process v2.8.6 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.8.7 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.8.8 conflicts with symfony/console[v3.4.3].
    - symfony/process v2.8.9 conflicts with symfony/console[v3.4.3].
    - Installation request for symfony/console (locked at v3.4.3) -> satisfiable by symfony/console[v3.4.3].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by duncan3dc** [comment]
What does your `composer.json` contain?

**Comment by waqadeer** [comment]
```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "dmstr/yii2-adminlte-asset": "2.*",
        "stripe/stripe-php": "^5.8"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }
        }
    }
}
```

**Comment by duncan3dc** [comment]
Try the following command instead:
```sh
composer require --update-with-dependencies duncan3dc/speaker
```

**Comment by waqadeer** [comment]
Besides it's working with my fresh php project (non-framework) and i want to know if there is an option to select the audio voice speaker person for e.g John (male) in english (UK, US, AUS, CA) etc

**Comment by duncan3dc** [comment]
I depends which provider you are using, but yes some of them support different voices, the documentation shows what each supports: http://duncan3dc.github.io/speaker/

**Comment by waqadeer** [comment]
ok i am done with installing/updating the dependencies. Now there is an issue with your Google Provider i.e. 
```
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET http://translate.google.com/translate_tts?q=Hello+World&tl=fr&client=duncan3dc-speaker` resulted in a `503 Service Unavailable` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...) in C:\laragon\www\tts\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\laragon\www\tts\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\laragon\www\tts\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\laragon\www\tts\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\laragon\www\tts\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promi in C:\laragon\www\tts\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
```

**Comment by duncan3dc** [comment]
Google is returning "Service Unavailable", so maybe they've taken their service down, or are blocking your requests
