### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by dausruddin** [duncan3dc/speaker#2]
I don't have any idea how to handle the errors. Currently, Im using GoogleProvider. 

When I entered a string like this: `sbsks nfpsosi skslsoj sksls`,
the script throw me errors:

```
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: 503' in /home/xxxx/public_html/api/tts/vendor/guzzlehttp/guzzle/src/Middleware.php:68 Stack trace: #0 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #1 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #2 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #3 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #4 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /home/xxxx/public_html/api/tts/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp in /home/xxxx/public_html/api/tts/vendor/guzzlehttp/guzzle/src/Middleware.php on line 68
```

**Comment by dausruddin** [comment]
This is my script

```
<?php
ini_set('display_errors', true);

require_once __DIR__ . "/vendor/autoload.php";

use duncan3dc\Speaker\TextToSpeech;
use duncan3dc\Speaker\Providers\GoogleProvider;


if(!isset($_GET['text'])){

  $text_error = array( "error" => "empty", "error_full" => "Sorry, I can't process an empty text.", "mp3" => "false");
  header('Content-Type: application/json');
  die(json_encode($text_error));

}elseif(preg_match('/[^a-z\s\.]/i', $_GET['text'])){ 

  $text_error = array( "error" => "invalid", "error_full" => "Only alphabets a-z are accepted", "mp3" => "false");
  header('Content-Type: application/json');
  die(json_encode($text_error));

 }elseif(preg_match('/[a-z\s\.]{101,}+/i', $_GET['text'])){

  $text_error = array( "error" => "exceed", "error_full" => "Your text have ".strlen($_GET['text'])." characters. Only 100 max is supported", "mp3" => "false");
  header('Content-Type: application/json');
  die(json_encode($text_error));

}else{

$text = $_GET['text'];

function randomNumber($length) { 
  $result = ''; 
  for($i = 0; $i < $length; $i++) { 
    $result .= mt_rand(0, 9);
  } return $result; 
}

$provider = new GoogleProvider;

if (!is_dir("mp3")) { 
    mkdir('mp3', 0755, true);
}

$filename = randomNumber(10);
$tts = new TextToSpeech($text, $provider);
$tts->save("mp3/".$filename.".mp3");


$data = array( "error" => "false", "error_full" => "false", "mp3" => "https://xxxx.com/api/tts/mp3/".$filename.".mp3");
//header('Content-Type: application/json');
echo json_encode($data);

}

?>
```

**Comment by dausruddin** [comment]
I realized that the errors spawn on all text I entered!!!
It works before this, somehow it throwing me those errors.

**Comment by dausruddin** [comment]
Is there any limitation on google tts other thab 100chars? Now your script just give me 503 server error no matter what I have tried.

**Comment by duncan3dc** [comment]
HTTP Error [503](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) is `"Service unavailable"`.

Maybe google took down the service, or changed it in some way. I'll take a look when I get a minute, but I'd recommend using one of the other [providers](http://duncan3dc.github.io/speaker/)

**Comment by dausruddin** [comment]
Yeah please. Now Im using Voxygen. It is working great :)

**Comment by duncan3dc** [comment]
I'm trying to reproduce your issue but I am unable to. Is this error still occurring? Maybe the google service was down when you last tried?

**Comment by dausruddin** [comment]
it is working now. 
is Google service was down or I was trying to many in certain period and ip was banned? It is little awkward if google has downtime in their services.

**Comment by duncan3dc** [comment]
Yes it will have been one of those reasons, the paid services are likely to be more reliable
